# Generated by Django 2.0.4 on 2018-07-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0002_auto_20180711_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息表'},
        ),
    ]
