# Generated by Django 2.0.4 on 2018-07-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0004_auto_20180711_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
