# Generated by Django 2.0.4 on 2018-07-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0005_auto_20180711_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set(),
        ),
    ]
