# Generated by Django 2.0.4 on 2018-07-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0007_auto_20180717_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together={('article', 'tag')},
        ),
    ]
